# Generated by Django 3.2.25 on 2024-03-18 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_score'),
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='posts.post'),
        ),
    ]
